service: aws-python-http-api-project
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  environment:
    AUTH_TOKEN: ${env:OPENAI_API_KEY}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-offline

